##An anagram number is a number that can be multiplied by at least one single digit number (other than 1) to become an anagram of itself. Any anagrams formed by multiplying an anagram number by a digit are said to be generated by that anagram number. Two numbers are anagrams of each other if they can both be formed by rearranging the same combination of digits.##
##For example:###
##• 1246878 is an anagram number; multiplying by 6 generates 7481268 or by 7 generates 8728146. These numbers all contain a single 1, 2, 4, 6, 7 and two 8s.##
##• 1246879 is not an anagram number.##
##Write  program with  GUI, using TKINTER ,  which takes a single number and determine if it is an anagram number. The number needs to be entered via entry box, while the result should be shown as a message box (not a label). .##
def anagram_numbers(num):
  isit=False
  sortd=sort(num)
  for i in range(2,9):
    mult=int(num)*i
    mult=sort(str(mult))
    if sortd==mult:
      isit=True
  return isit

def sort(number):
  new=""
  for n in range(len(number)):
    r=0
    while r<len(new):
      if int(new[r])>int(number[n]):
        start=new[:r]
        end=new[r:]
        new=start+number[n]+end
        r=len(new)
      r=r+1
    if r==len(new):
      new=new+number[n]
  return new

inputs=input("Number:")
print(anagram_numbers(inputs))
      
    


    