print("The Adventure")
noun1=input("Noun:")
noun2=input("Noun:")
noun3=input("Noun:")
noun4=input("Noun:")
adjective1=input("Adjective:")
adjective2=input("Adjective:")
adjective3=input("Adjective:")
adverb1=input("Adverb:")
adverb2=input("Adverb:")
food=input("Item of food:")
name1=input("Name:")
name2=input("Name:")
place=input("Place:")
emotion=input("Emotion:")
name="It can happpen to the best of us. It can happen to the worst of us. " + name1.capitalize() + " was a " + adjective1.lower() + " person. They loved "+ adverb1.lower() +" eating " + adjective2.lower() + " " + food.lower() + ". But one day at the " + adjective3.lower() + " " + place.capitalize() + ", they " + adverb2.lower() + " felt " + emotion.lower() + " beacuse of " + name2.capitalize() + "'s " + noun1.lower() + " and " + noun2.lower() + " but the worst thing was they fell over a " + noun3.lower() + " on top of " + noun4.lower() + ". That's how " + name1.capitalize() + " felt " + emotion.lower() + " today."
print(name)